### ISSUE TITLE
Error in Face_recog.py

### ISSUE THREAD

**Issue by ghost** [shobhitsrivastava-ds/Occlusion-based-face-detection#2]
PS C:\Users\Rapaka\Desktop\Occlusion-based-face-detection-master\Occlusion-based-face-detection-master> python .\Face_recog.py
[INFO]!! Testing the image !!
Traceback (most recent call last):
  File ".\Face_recog.py", line 20, in <module>
    rgb = cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty()
 in function 'cv::cvtColor'

**Comment by shobhitsrivastava-ds** [comment]
Running that in Linux(Ubuntu) I got no issue,
which Operating System are you using?
